services:
  - type: web
    name: downloader-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: NODE_ENV
        value: production

