services:
  - type: web
    name: downloader-backend
    runtime: node
    buildCommand: "npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
    nixPkgs:
      - ffmpeg
      - python3
